--------------------------------------------------------
-- Archivo creado  - martes-junio-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BL
--------------------------------------------------------

  CREATE TABLE "HR"."BL" 
   (	"ID_BL" NUMBER, 

	"NOMBRE_NAVE" VARCHAR2(20 BYTE), 

	"NUM_SELLO" NUMBER, 

	"CONSIGNATARIO" VARCHAR2(30 BYTE),
 
	"CONSIGNANTE" VARCHAR2(30 BYTE), 

	"PESO" NUMBER,
 
	"VOL_CUBICO" NUMBER,
 
	"MERCADERIA" VARCHAR2(20 BYTE), 

	"TIPO_CARGA" VARCHAR2(20 BYTE), 

	"FECHA_SALIDA" VARCHAR2(20 BYTE), 

	"FECHA_ARRIBO" VARCHAR2(20 BYTE), 

	"UNIDADES" NUMBER, 

	"CARGA" VARCHAR2(20 BYTE),
 
	"INCOTERMS" VARCHAR2(20 BYTE),
 
	"PAIS" VARCHAR2(20 BYTE),
 
	"DOCUMENTACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "HR"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER, 

	"NOMBRE_CL" VARCHAR2(50 BYTE),
 
	"DIRECCION" VARCHAR2(50 BYTE),
 
	"TELEFONO" NUMBER, 

	"EMAIL" VARCHAR2(30 BYTE), 

	"ID_COMUNA" VARCHAR2(20 BYTE),
 
	"ID_GIRO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "HR"."PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER,
 
	"NOMBRE_PROVEEDOR" VARCHAR2(50 BYTE),
 
	"ID_GIRO" VARCHAR2(30 BYTE), 

	"CONTACTO" NUMBER, 

	"EMAIL" VARCHAR2(50 BYTE), 

	"DIRECCION" VARCHAR2(50 BYTE), 

	"ID_COMUNA" NUMBER, 

	"ID_REG" NUMBER, 

	"ID_PAIS" VARCHAR2(20 BYTE), 

	"ID_TPROVEEDOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "HR"."ROL" 
   (	"ROL_ID" NUMBER, 

	"ROL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "HR"."USERS" 
   (	"USER_ID" NUMBER,
 
	"USERNAME" VARCHAR2(20 BYTE),
 
	"PASSWORD" VARCHAR2(100 BYTE),
 
	"ENABLED" NUMBER(1,0),
 
	"ROL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS_ROL
--------------------------------------------------------

  CREATE TABLE "HR"."USERS_ROL" 
   (	"USER_ID" NUMBER, 

	"ROL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AA_AGENTE_DE_ADUANA
--------------------------------------------------------

  CREATE TABLE "HR."AA_AGENTE_DE_ADUANA" 
   (	"ID_AGENTE" NUMBER, 
	"NOMBRE_AGENTE" VARCHAR2(60 BYTE), 
	"PAIS" VARCHAR2(20 BYTE), 
	"TIPO_TLC" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HR" ;
REM INSERTING into HR.BL
SET DEFINE OFF;
Insert into HR.BL (ID_BL,NOMBRE_NAVE,NUM_SELLO,CONSIGNATARIO,CONSIGNANTE,PESO,VOL_CUBICO,MERCADERIA,TIPO_CARGA,FECHA_SALIDA,FECHA_ARRIBO,UNIDADES,CARGA,INCOTERMS,PAIS,DOCUMENTACION) values ('1','Titanic','1','Test','Test','1','1','Hielo','Test','04/05/20','10/04/20','10','Test','Test','Chile','Test');
Insert into HR.BL (ID_BL,NOMBRE_NAVE,NUM_SELLO,CONSIGNATARIO,CONSIGNANTE,PESO,VOL_CUBICO,MERCADERIA,TIPO_CARGA,FECHA_SALIDA,FECHA_ARRIBO,UNIDADES,CARGA,INCOTERMS,PAIS,DOCUMENTACION) values ('2','Maria','1','Test','Test','1','1','Hielo','Test','04/08/20','10/04/20','10','Test','Test','Chile','Test');
Insert into HR.BL (ID_BL,NOMBRE_NAVE,NUM_SELLO,CONSIGNATARIO,CONSIGNANTE,PESO,VOL_CUBICO,MERCADERIA,TIPO_CARGA,FECHA_SALIDA,FECHA_ARRIBO,UNIDADES,CARGA,INCOTERMS,PAIS,DOCUMENTACION) values ('3','Pinta','1','Test','Test','1','1','Hielo','Test','04/05/20','10/04/20','10','Test','Test','Chile','Test');
Insert into HR.BL (ID_BL,NOMBRE_NAVE,NUM_SELLO,CONSIGNATARIO,CONSIGNANTE,PESO,VOL_CUBICO,MERCADERIA,TIPO_CARGA,FECHA_SALIDA,FECHA_ARRIBO,UNIDADES,CARGA,INCOTERMS,PAIS,DOCUMENTACION) values ('4','Niña','1','Test','Test','1','1','Hielo','Test','04/05/20','10/04/20','10','Test','Test','Chile','Test');
REM INSERTING into HR.CLIENTE
SET DEFINE OFF;
Insert into HR.CLIENTE (ID_CLIENTE,NOMBRE_CL,DIRECCION,TELEFONO,EMAIL,ID_COMUNA,ID_GIRO) values ('1','Juan','Test','123456','Test','Test','Test');
Insert into HR.CLIENTE (ID_CLIENTE,NOMBRE_CL,DIRECCION,TELEFONO,EMAIL,ID_COMUNA,ID_GIRO) values ('2','Alejandro','Test','123456','Test','Test','Test');
Insert into HR.CLIENTE (ID_CLIENTE,NOMBRE_CL,DIRECCION,TELEFONO,EMAIL,ID_COMUNA,ID_GIRO) values ('3','Diego','Test','123456','Test','Test','Test');
Insert into HR.CLIENTE (ID_CLIENTE,NOMBRE_CL,DIRECCION,TELEFONO,EMAIL,ID_COMUNA,ID_GIRO) values ('4','Sergio','Test','123456','Test','Test','Test');
REM INSERTING into HR.PROVEEDOR
SET DEFINE OFF;
Insert into HR.PROVEEDOR (ID_PROVEEDOR,NOMBRE_PROVEEDOR,ID_GIRO,CONTACTO,EMAIL,DIRECCION,ID_COMUNA,ID_REG,ID_PAIS,ID_TPROVEEDOR) values ('1','Nestle','Test','123','Test','Test','1','1','Test','Test');
Insert into HR.PROVEEDOR (ID_PROVEEDOR,NOMBRE_PROVEEDOR,ID_GIRO,CONTACTO,EMAIL,DIRECCION,ID_COMUNA,ID_REG,ID_PAIS,ID_TPROVEEDOR) values ('2','Disney','Test','123','Test','Test','1','1','Test','Test');
Insert into HR.PROVEEDOR (ID_PROVEEDOR,NOMBRE_PROVEEDOR,ID_GIRO,CONTACTO,EMAIL,DIRECCION,ID_COMUNA,ID_REG,ID_PAIS,ID_TPROVEEDOR) values ('3','Fox','Test','123','Test','Test','1','1','Test','Test');
Insert into HR.PROVEEDOR (ID_PROVEEDOR,NOMBRE_PROVEEDOR,ID_GIRO,CONTACTO,EMAIL,DIRECCION,ID_COMUNA,ID_REG,ID_PAIS,ID_TPROVEEDOR) values ('4','CNN','Test','123','Test','Test','1','1','Test','Test');
REM INSERTING into HR.ROL
SET DEFINE OFF;
Insert into HR.ROL (ROL_ID,ROL) values ('1','ROLE_ADMIN');
REM INSERTING into HR.USERS
SET DEFINE OFF;
Insert into HR.USERS (USER_ID,USERNAME,PASSWORD,ENABLED,ROL) values ('1','admin','$2y$12$qak4EFXxB0kbnz7JNbDkce9jGRwp.hIStBd1V4CA.O7pRIMA/xunS','1','ROLE_ADMIN');
REM INSERTING into HR.USERS_ROL
SET DEFINE OFF;
Insert into HR.USERS_ROL (USER_ID,ROL_ID) values ('1','1');
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ROL_PK" ON "HR"."ROL" ("ROL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."USERS_PK" ON "HR"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "HR"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ROL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."ROL" MODIFY ("ROL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "HR"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS_ROL
--------------------------------------------------------

  ALTER TABLE "HR"."USERS_ROL" ADD CONSTRAINT "USERS_ROL_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE;
 
  ALTER TABLE "HR"."USERS_ROL" ADD CONSTRAINT "USERS_ROL_FK2" FOREIGN KEY ("ROL_ID")
	  REFERENCES "HR"."ROL" ("ROL_ID") ENABLE;
